# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build fonts

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15"
      - name: ttfautohint
        run: sudo apt-get install -y ttfautohint
      - run: npm install
      - name: generate private config
        run: node generate-private-plans.js 2>plans-to-build.txt
      - name: Building fonts
        run: node ./node_modules/.bin/verda -f verdafile.js ttf::iosevka-vardanpro
      - name: uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-fonts
          path: |
            dist
            .build/.verda-build-journal
