# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build fonts

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Task to run (leave empty to run all)"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15"
      - name: ttfautohint
        run: sudo apt-get install -y ttfautohint
      - run: npm install
      - name: generate private config
        run: node generate-private-plans.js 2>plans-to-build.txt | tee private-build-plans.toml
      - name: patching libs
        run: |
          patch -p0 --binary < session.patch
      - name: Building fonts
        run: ./build-fonts.sh ${{ github.event.inputs.task }}
      - name: upload build logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-logs
          path: .build/
      - name: upload fonts
        uses: actions/upload-artifact@v2
        with:
          name: dist-fonts
          path: |
            dist/
